spring:
  datasource:
    jdbc-url: jdbc:mysql://39.98.137.182:3306/halodb?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: Lazylion0802.
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    schema:
      - "classpath:db/schema.sql"
    data:
      - "classpath:db/schema.sql"
    hikari:
      minimum-idle: 5
      connection-test-query: SELECT 1 FROM DUAL
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: SpringBootDemoHikariCP
      max-lifetime: 60000
      connection-timeout: 30000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
    open-in-view: true

logging:
  level:
    com.bytelion: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace