server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://39.98.137.182/bytelion?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    username: root
    password: Lazylion0802.
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.bytelion.detect.entity


Arc:
  face:
    appId: HsP7ZNwUWUyiW5s6QAAoCXnoysHNz9YBRGUEHJqKGqgC
    sdkKey: 8W1mzLwyHvbALUXPaKFBFAJMKnDCqSrCbwGPQTQMuctb
    libPath: F:\ArcSoft_ArcFace_Java_Windows_x64_V3.0\libs\WIN64
    basePath: D:\\Users\\Faceimage
#linux
#    sdkKey: 8W1mzLwyHvbALUXPaKFBFAJMBfe4hm77rbHzjFnooqu2
#    libPath: /root/test/libs/LINUX64
#    basePath: /root/test/libs/LINUX64

