
server:
  port: 8166
#数据源配置


#日志文件输出到文件
logging:
#  pattern:
#    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"
#    file: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"
#  指定日志文件存储位置
  path: /root/bytelion
  file:
    max-history: 60



