server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://39.98.137.182/ocean?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    username: Lazylion
    password: Lazylion0802.
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  thymeleaf:
    cache: false
logging:
  level:
    com.bytelion: debug
    com.bytelion.plus.mybatis.plus.*.mapper: trace

mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/bytelion/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.bytelion.**.entity
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      table-underline: true
      db-type: mysql
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

